### ISSUE TITLE
笑死，审计报告仓库地址都是错的，假的果然真不了

### ISSUE THREAD

**Issue by ChrisXYF** [htmoon/htmoon-contracts#3]
![mmexport1620921624178](https://user-images.githubusercontent.com/38465558/118155648-10267700-b3de-11eb-8f4e-d69b0585e3cf.jpg)

代码库明明是隔壁的htmoon-sdk，你审计contract竟然能把结果审出来，果然666

**Comment by wtongxue0** [comment]
应该是这个地址吧，safemoon也是. sol

**Comment by AegisZhu** [comment]
sdk那是工具包，是这个.sol
