### ISSUE TITLE
certik上怎么查不到啊

### ISSUE THREAD

**Issue by Crypto-KK** [htmoon/htmoon-contracts#6]

**Comment by wtongxue0** [comment]
现在可以了

**Comment by Aicxz** [comment]
@PanpAn006 你是小韭菜？

**Comment by wtongxue0** [comment]
> @PanpAn006 你是小韭菜？

没被割呢

**Comment by Aicxz** [comment]
> > @PanpAn006 你是小韭菜？
> 
> 没被割呢

没呢，微信二群解散了，有新群吗？我要回到家人的怀抱，感受家人的温暖！

**Comment by wtongxue0** [comment]
> > > @PanpAn006 你是小韭菜？
> > 
> > 没被割呢
> 
> 没呢，微信二群解散了，有新群吗？我要回到家人的怀抱，感受家人的温暖！

我加了个小群，要加的话发我微信拉你

**Comment by Aicxz** [comment]
> > > > @PanpAn006 你是小韭菜？
> > > 
> > > 
> > > 没被割呢
> > 
> > 
> > 没呢，微信二群解散了，有新群吗？我要回到家人的怀抱，感受家人的温暖！
> 
> 我加了个小群，要加的话发我微信拉你

你微信账号异常，没办法加好友，要不你发个二维码，或者你加我，vx：zhengpq81111

**Comment by wtongxue0** [comment]
> > > > > @PanpAn006 你是小韭菜？
> > > > 
> > > > 
> > > > 没被割呢
> > > 
> > > 
> > > 没呢，微信二群解散了，有新群吗？我要回到家人的怀抱，感受家人的温暖！
> > 
> > 我加了个小群，要加的话发我微信拉你
> 
> 你微信账号异常，没办法加好友，要不你发个二维码，或者你加我，vx：zhengpq81111

加你了
